spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: validate #Eğer Create olursa tabloyu baştan yaratır
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: pass
    driverClassName: org.postgresql.Driver
server:
  error:
    include-message: always
