spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate #Eğer Create olursa tabloyu baştan yaratır
    datasource:
      url: jdbc:mysql://localhost:3306/database
      username: root
      password: pass
      driverClassName: com.mysql.jdbc.Driver
server:
  error:
    include-message: always
